// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcqnafdoqpjxadppxufh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jcW5hZmRvcXBqeGFkcHB4dWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzkyNDgsImV4cCI6MjA1OTcxNTI0OH0.q1WsCLGraDUll3t3zzhDUtcYTPsdAYIC7ZqfbADu4Vc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);